#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOMAINS_FILE="${1:-$SCRIPT_DIR/../configs/domains.txt}"
OUT_FILE="$SCRIPT_DIR/../configs/dnsmasq-openai.conf"

extract_host() {
  local line="$1"
  # strip scheme
  line="${line#*://}"
  # strip path
  echo "${line%%/*}"
}

{
  echo "# Generated by render_dnsmasq_from_domains.sh from $(basename "$DOMAINS_FILE")"
  while IFS= read -r raw || [[ -n "$raw" ]]; do
    line="${raw%%#*}"; line="${line//[$'\t\r\n ']}"
    [[ -z "$line" ]] && continue
    host=$(extract_host "$line")
    [[ -z "$host" ]] && continue
    echo "ipset=/$host/openai,openai6"
  done < "$DOMAINS_FILE"
} > "$OUT_FILE"

echo "Wrote $OUT_FILE"
